# Generated by Django 5.0.3 on 2024-04-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carbrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('carbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carinfo.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('ban_type', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('gearbox', models.CharField(max_length=50)),
                ('transmitter', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('count_seats', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('carbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbrand', to='carinfo.carbrand')),
                ('subcarbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcarbrand', to='carinfo.subcarbrand')),
            ],
        ),
    ]
