# Generated by Django 5.0.3 on 2024-04-01 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='price_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
